Improved data fetchers bash command file

diff --git a/server/data_fetcher/run b/server/data_fetcher/run
--- a/server/data_fetcher/run
+++ b/server/data_fetcher/run
@@ -1,6 +1,7 @@
 #!/bin/bash
 
 # Compile using TypeScript
+npm i || { echo "Error: Installation failed"; exit 1; }
 npx tsc || { echo "Error: Compilation failed"; exit 1; }
 
 echo "DONE Compiling Data Fetcher 🛠️"
